module.exports = {
	entry:{
		home:'./src/entry/home.js',
		recycle:'./src/entry/recycle.js',
		personal:'./src/entry/personal.js',
	},
	output:{
		path:'./contents/js/',
		filename:'[name].js',
	},
	module:{
		loaders:[
			{
				test:/\.vue$/,
				loader:'vue-loader',
				options:{
					css:'css!autoprefixer',
					html:'html-loader',
				},
			},
			{
				test:/\.js$/,
				exclude:/node_modules/,
				loader:'babel-loader',
				options:{
					presets:['es2015'],
				},
			},
			{
				test:/\.json$/,
				exclude:/node_modules/,
				loader:'json-loader',
			},
			{
				test:/\.svg$/,
				loader:'url-loader?limit=40000',
			}
		],
	},
	resolve:{
		extensions:['.js','.vue'],
	},
	externals:{
		vue:'Vue',
	},
}